### PR TITLE
Todo List

### PR DESCRIPTION
**Pull request by janis-jenny**
- [ ]  Add Todos and Project classes
- [ ]  Add loaders and plugins
- [ ]  Add render and index.js
- [ ]  Add storage and push the projects and todos 
- [ ]  Refactor method and functions 

PS.

- [ ]  The project is not completed yet, but I'm submitting this to not get a low and received feedback about what I got until now. Thanks

### CODE REVIEW

**Review by trekab — COMMENTED** [review]
### Invalid! :stop_sign: 
Hi team! Unfortunately, I have to invalidate your code review request because you still have failing linter checks on your PR. ([Zendesk Announcement](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-#))

__Please make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Review by trekab — CHANGES_REQUESTED** [review]
**Changes Required!** :recycle: 
Hi team! Thank you for explaining why your project is incomplete in your PR message! :+1: I think you're on the right track and it is totally fine to ask for feedback sooner. I'll highlight some points below for you to work on in order to finish this project:
* [ ] Improve the content of your `README.md` file to at least include instructions for running your project locally. [Here](https://github.com/trekab/readme-template) is a nice template you could use.
* [ ] I was unable to get any dom elements loaded when I tried to use your `npm` scripts to run the app. The console indicated an `Uncaught TypeError: Cannot read property 'addEventListener' of null`.
* [ ] You are expected to make use of ES6+ syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/es6_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/)). I have noticed that you used the function keyword in the `render.js` module rather than using the preferred arrow function syntax.

**Note:** Unfortunately, most of the feedback depends on the app being able to at least run without errors. I hope you are able to make more progress with the feedback above.

__Please make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Review by afanimartin — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Nice work making the requested changes.
The codebase follows ES6 syntax and a user can now create a new project. Well done!
Let's make some changes so we can merge this PR.
- [ ] I was not able to create a new task. I got these errors:
```javascript
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
localhost/:1 Error handling response: TypeError: Cannot destructure property 'yt' of 'undefined' as it is undefined.
    at chrome-extension://cmedhionkhpnakcndndgjdbohmhepckk/scripts/contentscript.js:513:6
render.js:31 Uncaught TypeError: Cannot read property 'remove' of null
    at HTMLButtonElement.eval (render.js:31)
2renderTasks.js:9 Uncaught TypeError: Cannot read property 'tasks' of undefined
    at addTodo (renderTasks.js:9)
    at HTMLButtonElement.eval (render.js:114)
```
- [ ] Update the readme file. Right now it lacks information required to start the app locally. Use the template given by the previous reviewer.


### Martin Afani
#### Slack: whiz25

**Review by rukundoeric — APPROVED** [review]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - Follows gitwork-flow. 💯 
  - App is deployed and working online. 💯 

- ### To Improve
  - [ ] [Mandatory] There is a broken image in your readme, kindly fix it before you merge.

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Pull request merged**
